# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

before_all do
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "fiss-uctd-crby-zqvz"
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    begin
      app_store_connect_api_key(
    key_id: "62Z8K7W67N",
    issuer_id: "69a6de88-4a18-47e3-e053-5b8c7c11a4d1",
    key_filepath: "./fastlane/AuthKey_62Z8K7W67N.p8",
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )
    increment_build_number(
      xcodeproj: "Runner.xcodeproj",
      build_number: latest_testflight_build_number + 1
    )
    build_app(
	workspace: "Runner.xcworkspace", 
	scheme: "Runner",
	clean: true,
      configuration: "Release",
      include_bitcode: false,
      build_path: "fastlane/delivery/testflight/",
      archive_path: "fastlane/delivery/testflight/",
      derived_data_path: "fastlane/delivery/testflight/",
      output_directory: "fastlane/delivery/testflight/",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.acaziasoft.spendy" => "Spendy Money Tracker",
        }
      }
)
    upload_to_testflight(
      beta_app_feedback_email: "quangtt@acaziasoft.com",
    	demo_account_required: false,
        beta_app_review_info: {
        contact_email: "quangtt@acaziasoft.com",
        contact_first_name: "Quang",
        contact_last_name: "Tran",
        contact_phone: "+84982966192"
      },
      notify_external_testers: true,
	skip_waiting_for_build_processing:true,
	apple_id: "1506769608",
      	username: "tranthequangbk@gmail.com",
	team_id: "117957836"
    )
    on_success()
    rescue => exception
         on_error(exception)
      end
  end
end

def on_error(exception)
   slack(
       message: "Spendy App",
       success: false,
       slack_url: "https://hooks.slack.com/services/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",
       attachment_properties: {
           fields: [
               {
                   title: "Build number",
                   value: ENV["BUILD_NUMBER"],
               },
               {
                   title: "Error message",
                   value: exception.to_s,
                   short: false
               }
           ]
       }
   )
end

def on_success()
   slack(
       message: "Build Spendy App success",
       success: true,
       slack_url: "https://hooks.slack.com/services/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",
       attachment_properties: {
           fields: [
               {
                   title: "Build number",
                   value: ENV["BUILD_NUMBER"],
               },
               {
                   title: "Build Success",
                   value: "Build Successfully",
                   short: false
               }
           ]
       }
   )
end

